spring:
  ai:
    mistralai:
      api-key: ${MISTRALAI_API_KEY}
    openai:
      api-key: ${OPENAI_API_KEY}

  main:
    banner-mode: off
    web-application-type: none

logging:
  pattern:
    console:
